name: test
'on':
  schedule:
    - cron: 0 22 * * *
  workflow_dispatch:
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: check_code
        uses: actions/checkout@master
      - name: set up Python 3.8
        uses: actions/setup-Python@v2
        with:
          python-version: '3.8'
      - name: install requirements
        run: |
          pip install selenium
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: process data
        run: |
          python ./japan_selenium.py
      - name: commit and push if it changed
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          git commit -m 'updated'
          git push
